service: aws-upload-s3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    BUCKET_NAME: your-bucket-name
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "arn:aws:s3:::your-bucket-name/*"

functions:
  upload:
    handler: handler.upload
    events:
      - httpApi:
          path: /upload
          method: post

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    target: node18
    platform: node
    sourcemap: true
    exclude: ['aws-sdk']
